### ISSUE TITLE
Project Part 1 Trouble Generating Sliding

### ISSUE THREAD

**Issue by sarahbashir** [mikeizbicki/cmc-csci181#29]
I get this error when I attempt to run my code:

```
Traceback (most recent call last):
  File "names.py", line 547, in <module>
    infer(line)
  File "names.py", line 466, in infer
    explain(line, path_base+'.char.png', 'char')
  File "names.py", line 485, in explain
    while line[j] in string.ascii_letters:
IndexError: string index out of range
```

This is my code to generate the scores for the letters and words:
```
for i in range(len(line)):
        #char
        input_tensor[i][0][vocabulary.find(line[i])] = 0
        output_class,output_nextchars = model(input_tensor)
        new_probs = softmax(output_class)
        scores[i] = torch.dist(probs,new_probs,2)

        #word
        j = i
        #if there's a letter
        while line[j] in string.ascii_letters:
            input_tensor[j][0][vocabulary.find(line[j])] = 0
            output_class,output_nextchars = model(input_tensor)
            new_probs = softmax(output_class)
            scores[j] = torch.dist(probs,new_probs,2)
            j+=1

    line2img(line,scores,filename)

```

I'm assuming the error is from how I'm incrementing j, but when I try it another way the code just runs and doesn't generate anything, also not generating error messages..

Would appreciate some guidance with where I could be going wrong. Thanks!

**Comment by mikeizbicki** [comment]
In your while loop, you're going beyond the length of `line`, so you just need to add a check to make sure you are still in the `line`.

**Comment by sarahbashir** [comment]
I was able to fix the out of bounds error but my results for the word and character images is really off. It's generating the same green boxes for words and characters. It also seems like the weights are not changing so I assume something is wrong with how I'm constructing my scores vector?

![image](https://user-images.githubusercontent.com/47167558/80139188-e42e1e80-855a-11ea-814c-f073648831c4.png)

This is the result of printing out scores (which makes sense):

```tensor([0.0000, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391,
        0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391,
        0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391,
        0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391,
        0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391,
        0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391,
        0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391, 0.0391],
       grad_fn=<CopySlices>)
```

Just not sure where I'm going wrong when I'm generating the scores for words and charactes.
