### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by raequan** [mikeizbicki/cmc-csci181#48]
I am getting an error running the transformers_tutorial.py.

I haven't edited anything so far, but I run it and I get the error: 

```Traceback (most recent call last):
  File "transformers_tutorial.py", line 38, in <module>
    crash
NameError: name 'crash' is not defined```
```

Is there any help I can have with this?

**Comment by kielong** [comment]
crash is just there so that the code stops running at that point. You can just comment it out, it's not an actual function.
